### ISSUE TITLE
update webpack config to webpack5

### ISSUE THREAD

**Issue by timea-solid** [solid/solid-panes#321]
Upon local testing I followed the advice on https://github.com/solid/solid-panes#development
I get errors:
![Screenshot 2021-12-10 at 15 13 31](https://user-images.githubusercontent.com/4144203/145595003-166ff889-14a4-4654-ade6-63ffe6ce5826.png)
The problem is not in profile-pane which was updated to webpack5. It is because solid-panes webpack config is not updated.

**Comment by josephguillaume** [comment]
Sorry, I was naughty and also updated the webpack config in https://github.com/solid/solid-panes/pull/320

The profile-pane on GitHub works fine, i.e. those errors have been fixed but not yet published to npm
I fixed the profile-pane errors locally within a solidos environment by using
npm run add profile-pane
npx lerna bootstrap --force-local

There might have been a build step in there somewhere too.
And obviously I had to manually select the form pane and point it at a test file.
Not sure if there's a way for me to share my test environment.
